### ISSUE TITLE
BitSequence Encoding

### ISSUE THREAD

**Issue by tjjfvi** [paritytech/parity-scale-codec-ts#55]
???

https://github.com/paritytech/scale-value/blob/main/src/scale_impls/bit_sequence.rs
https://github.com/paritytech/scale-value/blob/main/src/scale_impls/encode.rs#L541
https://github.com/paritytech/scale-value/blob/main/src/scale_impls/decode.rs#L281

**Comment by harrysolovay** [comment]
Upon implementing encoding, we must also remove the bitSequence-specific test ignores.
